steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/rapid-stage-425307-j4/my-python-api', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/rapid-stage-425307-j4/my-python-api']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'my-python-api', '--image', 'gcr.io/rapid-stage-425307-j4/my-python-api', '--platform', 'managed']
